# Generated by Django 3.2.5 on 2021-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Activate'), (0, 'Deactivate')], default=1)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
