STATUS_ACTIVATE = 1
STATUS_DEACTIVATE = 0
STATUS_CHOICES = (
    (STATUS_ACTIVATE, 'Activate'),
    (STATUS_DEACTIVATE, 'Deactivate'),
)

TYPE_ELEMENT_EMPTY = '0'
TYPE_ELEMENT_EMPTY_CLIC = '1'
TYPE_ELEMENT_MINE = '2'
TYPE_ELEMENT_MINE_CLIC = '3'
TYPE_ELEMENT_NUMBER = '4'
TYPE_ELEMENT_NUMBER_CLIC = '5'
TYPE_ELEMENT_FLAG = '6'
TYPE_ELEMENT_MINE_FLAG = '7'
TYPE_ELEMENT_BOARD_CHOICES = (
    (TYPE_ELEMENT_EMPTY, 'TYPE_ELEMENT_EMPTY'),
    (TYPE_ELEMENT_EMPTY_CLIC, 'TYPE_ELEMENT_EMPTY_CLIC'),
    (TYPE_ELEMENT_MINE, 'TYPE_ELEMENT_MINE'),
    (TYPE_ELEMENT_MINE_CLIC, 'TYPE_ELEMENT_MINE_CLIC'),
    (TYPE_ELEMENT_NUMBER, 'TYPE_ELEMENT_NUMBER'),
    (TYPE_ELEMENT_NUMBER_CLIC, 'TYPE_ELEMENT_NUMBER_CLIC'),
    (TYPE_ELEMENT_FLAG, 'TYPE_ELEMENT_FLAG'),
    (TYPE_ELEMENT_MINE_FLAG, 'TYPE_ELEMENT_MINE_FLAG'),
)

RESULT_BOARD_PENDING = '1'
RESULT_BOARD_WIN = '2'
RESULT_BOARD_LOST = '3'
RESULT_BOARD_CHOICES = (
    (RESULT_BOARD_PENDING, 'RESULT_BOARD_PENDING'),
    (RESULT_BOARD_WIN, 'RESULT_BOARD_WIN'),
    (RESULT_BOARD_LOST, 'RESULT_BOARD_LOST'),
)
