# Generated by Django 3.2.5 on 2021-07-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dragamina', '0002_auto_20210704_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameGameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Activate'), (0, 'Deactivate')], default=1)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('game_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragamina.gameboard')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
