# Generated by Django 3.2.5 on 2021-07-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragamina', '0003_usernamegameboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementGameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Activate'), (0, 'Deactivate')], default=1)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('type_element', models.CharField(choices=[(0, 'TYPE_ELEMENT_EMPTY'), (1, 'TYPE_ELEMENT_EMPTY_CLIC'), (2, 'TYPE_ELEMENT_MINE'), (3, 'TYPE_ELEMENT_MINE_CLIC'), (4, 'TYPE_ELEMENT_NUMBER'), (5, 'TYPE_ELEMENT_NUMBER_CLIC'), (6, 'TYPE_ELEMENT_FLAG'), (7, 'TYPE_ELEMENT_FLAG_CLIC')], default=0, max_length=3)),
                ('game_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragamina.gameboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
