# Generated by Django 3.2.5 on 2021-07-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragamina', '0004_elementgameboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='result',
            field=models.CharField(choices=[('1', 'RESULT_BOARD_PENDING'), ('2', 'RESULT_BOARD_WIN'), ('3', 'RESULT_BOARD_LOST')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='elementgameboard',
            name='game_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='dragamina.gameboard'),
        ),
    ]
