# Generated by Django 3.2.5 on 2021-07-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragamina', '0005_auto_20210706_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementgameboard',
            name='type_element',
            field=models.CharField(choices=[('0', 'TYPE_ELEMENT_EMPTY'), ('1', 'TYPE_ELEMENT_EMPTY_CLIC'), ('2', 'TYPE_ELEMENT_MINE'), ('3', 'TYPE_ELEMENT_MINE_CLIC'), ('4', 'TYPE_ELEMENT_NUMBER'), ('5', 'TYPE_ELEMENT_NUMBER_CLIC'), ('6', 'TYPE_ELEMENT_FLAG'), ('7', 'TYPE_ELEMENT_MINE_FLAG')], default='0', max_length=3),
        ),
    ]
